.TH occt-draw 1 "OpenCASCADE command interpreter and graphical test system" "DEBIAN" \" -*- nroff -*-
.SH NAME
occt-draw \- OpenCASCADE command interpreter and graphical test system
.SH SYNOPSIS
\fBocct-draw\fP
.SH DESCRIPTION
This program provides a kind of scripting interface to the OpenCASCADE
libraries.  You can perform a simple test by starting it and entering at the
command line: "pload ALL" then "source /usr/share/occt/7.5.2/src/DrawResources/VisualizationDemo.tcl".
.SH AUTHOR
Adam Powell <hazelsct@debian.org>
